// Slider
export const SET_SLIDER_SETTINGS = 'SET_SLIDER_SETTINGS'
// Home
export const SET_MOST_POPULAR_MOVIES = 'SET_MOST_POPULAR_MOVIES';
export const SET_MOVIES = 'SET_MOVIES';
export const SET_GET_MOVIES_ERROR = 'SET_GET_MOVIES_ERROR';
export const SET_MOVIES_IN_THEATERS = 'SET_MOVIES_IN_THEATERS';
